---
- name: "Pull lab code from {{ lab_repo.clone_url }}"
  git:
    repo: "{{ lab_repo.clone_url }}"
    dest: "{{ lab_repo.target_path }}"

- include: "cassandra/build-and-push.yml"
  when: '"cassandra" in required_containers'

- include: "hadoop/build-and-push.yml"
  when: '"hadoop" in required_containers'