---
docker_image: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/panda-toolbox:{{ toolbox.docker_tag }}"
docker_instance_name: panda-toolbox

# Docker pre-image variables
host_base_folder: "{{ toolbox.host.folders.base }}"
host_data_folders:
  config_hadoop: "{{ toolbox.host.folders.config }}/hadoop"
  state: "{{ toolbox.host.folders.state }}"