---
topic_default:
  prefix: "org.digitalpanda"
  partitions: 6
  replication_factor: 2

topics:
  - name: "org.digitalpanda.measure.raw-1-sec"
    partitions: "6"
    replication_factor: "2"
    config:
      cleanup.policy: delete
      retention.ms: 3153600000000
      segment.bytes: 33554432
    avro:
      value_schema_file: "raw-measure.avsc"

  - name: "org.digitalpanda.measure.processed-1-sec"
    partitions: "6"
    replication_factor: "2"
    config:
      cleanup.policy: delete
      retention.ms: 15552000
      segment.bytes: 33554432
    avro:
      value_schema_file: "measure.avsc"

  - name: "org.digitalpanda.measure.processed-1-min"
    partitions: "6"
    replication_factor: "2"
    config:
      cleanup.policy: delete
      retention.ms: 15552000
      segment.bytes: 33554432
    avro:
      value_schema_file: "measure.avsc"

  - name: "org.digitalpanda.measure.processed-1-hour"
    partitions: "6"
    replication_factor: "2"
    config:
      cleanup.policy: delete
      retention.ms: 15552000
      segment.bytes: 33554432
    avro:
      value_schema_file: "measure.avsc"

  - name: "org.digitalpanda.measure.processed-6-hour"
    partitions: "6"
    replication_factor: "2"
    config:
      cleanup.policy: delete
      retention.ms: 15552000
      segment.bytes: 33554432
    avro:
      value_schema_file: "measure.avsc"

avro_schema_folder: "{{ role_path }}/../../../digitalpanda-common/src/main/avro"


flink_session_yarn_application_name: "flink-session-daemon"
sensor_digestion_flink_path: "{{ role_path }}/../../../digitalpanda-bigdata/sensor-digestion-flink"