---
- name: "Prepare environment for docker instance"
  include_role:
    name: docker-pre-image


- name: "Pull image 'digitalpanda-backend:{{ digitalpanda_backend_version }}' and (re)start container with name '{{ docker_instance_name }}'"
  docker_container:
    name: "{{ docker_instance_name }}"
    state: started
    pull: true
    restart: yes
    image: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/digitalpanda-backend:{{ digitalpanda_backend_version }}"
    env:
      TARGET_ENV: "local"
    command: >-
      sh -c 'java -jar -Dspring.profiles.active=container.${TARGET_ENV} ${BIN_DIR}/backend.jar'
    volumes:
      - "{{host_data_folders.log}}:/opt/backend/log"
    ports:
      - "8081:8081"
    network_mode: bridge
    networks:
      - name: digitalpanda
    restart_policy: on-failure
    restart_retries: 50
    tty: yes
  when: not (absent_from_node | bool)
