---
- name: "Prepare environment for docker instance"
  include_role:
    name: docker-pre-image

- name: "Add hadoop global configuration files on host"
  template:
    src: "{{ role_path }}/../hadoop-common/templates/{{ item }}.j2"
    dest: "{{ host_data_folders.config_hadoop }}/{{ item }}"
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
  when: not (absent_from_node | bool)

- name: "Add misc. configuration files on host"
  template:
    src: "{{ item }}"
    dest: "{{ toolbox.host.folders.config }}/{{ item }}"
  with_items:
    - jupyter_notebook_config.py
  when: not (absent_from_node | bool)

- name: "Pull image {{ docker_image }} and (re)start container {{ docker_instance_name }}"
  become: yes
  docker_container:
    name: "{{ docker_instance_name }}"
    state: started
    pull: true
    command: >-
      bash -c
      "source ${JUPYTERLAB_BIN_FOLDER}/jupyter-lab-env/bin/activate;
      jupyter lab
      --config=${TOOLBOX_CONFIG}/jupyter_notebook_config.py;"
    restart: yes
    image: "{{ docker_image }}"
    volumes:
      - "{{ host_base_folder }}:{{ toolbox.container.exposed_folder.base }}"
    env:
      CQLSH_HOST: "{{ groups['cassandra_node'][0] }}"
    network_mode: host
    restart_policy: always
    tty: yes
  when: (not (absent_from_node | bool))