---
- hosts: x64_build_node
  roles:
    - { role: docker-registry,
        required_containers: ['cassandra'] ,
        when: (build_code | default(False) | bool)}

- hosts: cassandra_nodes
  roles:
   - cassandra

- hosts: backends
  roles:
    - digitalpanda-backend

- hosts: cassandra_test_data_injector
  roles:
  - { role: test-data-injector,
      when: (inject_test_data | default(False) | bool)}

- hosts: frontends
  roles:
  - { role: digitalpanda-frontend,
      when: (deploy_frontend | default(False) | bool) }




