---
# This role sets up a user for the cluster configuration and sets up the ssh accesses
-
- name: "Update repositories cache and install base packages"
  become: yes
  apt:
    name:
     - docker.io=18.09.7-0ubuntu1~18.04.4
     - python-dockerpty
    update_cache: yes

- name: "Unmask, enable & start docker service "
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no

- name: "Ensure group 'docker' exists"
  become: yes
  ansible.builtin.group:
    name: docker
    state: present

- name: "Create cluster user: {{ cluster_user }}"
  become: yes
  user:
    name: "{{ cluster_user }}"
    uid: "{{ cluster_user_id }}"
    create_home: True
    groups:
      - "{{ cluster_user }}"
      - docker
    comment: "Cluster account"
    generate_ssh_key: yes

- name: "Register ssh autorized_keys into {{ cluster_user }}"
  become: yes
  authorized_key:
    user: "{{ cluster_user }}"
    state: present
    key: '{{ item }}'
  with_items: "{{ authorized_keys }}"

- name: "Copy static host name resolution file & define node FQDN"
  become: yes
  template:
    src: ./templates/network/hosts
    dest: /etc/hosts
    owner: root
    mode: "u=rw,g=r,o=r"

- name: "Copy wired network ip configuration file"
  become: yes
  template:
    src: ./templates/network/01-netcfg.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    mode: "u=rw,g=r,o=r"
  when: static_ip

- name: "Apply wired network ip configuration"
  become: yes
  shell: netplan --debug apply

- name: "copy custom Docker configuration"
  become: yes
  template:
    src: templates/docker/daemon.json
    dest: /etc/docker/daemon.json